export { view_client_details } from './view_client_details.js';
export { create_client_address_car } from './create_client_address_car.js';
export { delete_client_car } from './delete_client_car.js'
export { update_client_address } from './update_client_address.js';
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";

export let options = {
    scenarios: {
        view_client_details: { // some arbitrary scenario name
            executor: 'ramping-vus', // Executor type is dependent on the scenario https://k6.io/docs/using-k6/scenarios/executors/
            stages: [
                { duration: '1m', target: 15 },
                { duration: '1m', target: 15 },
                { duration: '1m', target: 0 },
            ],
            tags: { test: 'view_client_details' }, // extra tags for the metrics generated by this scenario
            exec: 'view_client_details', // the function this scenario will execute
        },
        create_client: {
            executor: 'ramping-vus',
            stages: [
                { duration: '1m', target: 5 },
                { duration: '1m', target: 5 },
                { duration: '1m', target: 0 },
            ],
            tags: { test: 'create_client' },
            exec: 'create_client_address_car', // this scenario is executing a different function!
        },
        delete_car: {
            executor: 'ramping-vus',
            stages: [
                { duration: '1m', target: 2 },
                { duration: '1m', target: 2 },
                { duration: '1m', target: 0 },
            ],
            tags: { test: 'delete_car' },
            exec: 'delete_client_car', // this scenario is executing a different function!
        },
        update_address: {
            executor: 'ramping-vus',
            stages: [
                { duration: '1m', target: 1 },
                { duration: '1m', target: 1 },
                { duration: '1m', target: 0 },
            ],
            tags: { test: 'update_address' },
            exec: 'update_client_address', // this scenario is executing a different function!
        },
    },
    thresholds: { // Each scenario can have its own thresholds
        'http_req_duration{test:view_client_details}': ['p(90)<200', 'p(99)<500'],
        'http_req_failed{test:view_client_details}': ['rate<0.1'],
        'http_req_duration{test:create_client}': ['p(90)<200', 'p(99)<350'],
        'http_req_failed{test:create_client}': ['rate<0.05'],
        'http_req_duration{test:delete_car}': ['p(90)<300', 'p(99)<500'],
        'http_req_failed{test:delete_car}': ['rate<0.1'],
        'http_req_duration{test:update_address}': ['p(90)<300', 'p(99)<500'],
        'http_req_failed{test:update_address}': ['rate<0.1'],
    }
};


export function handleSummary(data) {
    console.log('Preparing the end-of-test summary...');
  
    // Send results to external location
    /*
      const res = http.post('https://[enter-url-here]', JSON.stringify(data));
      if (res.status != 200) {
        console.error('Could not send summary, got status ' + res.status);
      }
  */
  
    return { "summary.html" : htmlReport(data)}
  }
